version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: finedu_db
      POSTGRES_USER: finedu_user
      POSTGRES_PASSWORD: finedu_password
    ports:
      - "5433:5432"