"""
Django settings for finedu_core project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Render'da SECRET_KEY ortam değişkeni tanımlıysa o kullanılır; tanımlı
# değilse (yerel geliştirme) eski gömülü anahtara düşer.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-nid!p@121jji@!s&t#zuqe_c%%3z$^_5)#2iv06t5vnvpe!3sw',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Varsayılan False (güvenli); yerel geliştirmede terminalde
# `DEBUG=True` set edip runserver'ı öyle çalıştırabilirsin.
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Render'da ALLOWED_HOSTS ortam değişkeni tanımlıysa onu, değilse yerel
# geliştirme + bilinen prod backend adresini kullan.
ALLOWED_HOSTS = os.environ.get(
    'ALLOWED_HOSTS',
    'localhost,127.0.0.1,finedu-project.onrender.com',
).split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'accounts',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'finedu_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'finedu_core.wsgi.application'


# Database

DATABASES = {
    # Eğer sistemde bir DATABASE_URL (Neon.tech linki) varsa onu kullan, 
    # yoksa (kendi bilgisayarında test ediyorsan) eski sqlite3'ü kullan.
    'default': dj_database_url.config(
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.CustomUser'

# Render'da CORS_ALLOWED_ORIGINS ortam değişkeni tanımlıysa onu, değilse
# yerel geliştirme + prod Vercel adresini kullan. Yeni bir domain eklenirse
# (özel domain vb.) Render'da ortam değişkeniyle override edilebilir.
CORS_ALLOWED_ORIGINS = os.environ.get(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,https://finedu-project.vercel.app',
).split(',')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Chatbot dış API'ye (OpenAI) senkron istek attığı için kullanıcı
        # başına sınırlanmazsa tek worker'ı art arda isteklerle kilitleyebilir.
        'chatbot': '5/min',
    },
}

# settings.py dosyasının en altı
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CLOUDINARY BULUT DEPOLAMA AYARLARI
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}

STORAGES = {
    "default": {
        # Videoları ve medyaları Cloudinary'ye gönderir
        "BACKEND": "cloudinary_storage.storage.VideoMediaCloudinaryStorage",
    },
    "staticfiles": {
        # Statik dosyaları (CSS, JS) normal klasörde tutar
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}