# Generated by Django 5.2.11 on 2026-03-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_classroom_created_at_classroom_grade_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='grade_level',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('GAME', 'Oyun/Simülasyon')], max_length=55),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('PRIMARY', 'İlkokul'), ('MIDDLE', 'Ortaokul'), ('HIGH', 'Lise'), ('UNIVERSITY_FINANCE', 'Üniversite (Finans/İşletme)'), ('UNIVERSITY_GENERAL', 'Üniversite (Genel)')], max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Öğretmen'), ('STUDENT', 'Öğrenci')], default='STUDENT', max_length=55),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='student_code',
            field=models.CharField(blank=True, max_length=55, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='target_grade',
            field=models.CharField(choices=[('PRIMARY', 'İlkokul'), ('MIDDLE', 'Ortaokul'), ('HIGH', 'Lise'), ('UNIVERSITY_FINANCE', 'Üniversite (Finans/İşletme)'), ('UNIVERSITY_GENERAL', 'Üniversite (Genel)')], max_length=55),
        ),
    ]
