# Generated by Django 5.2.11 on 2026-03-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_classroom_grade_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='video_url',
        ),
        migrations.AddField(
            model_name='content',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
