# Generated by Django 5.2.11 on 2026-03-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_content_video_url_content_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='game_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
