# Generated by Django 5.2.11 on 2026-03-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_content_game_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='game_code',
            field=models.CharField(blank=True, choices=[('financial_detective', '🕵️\u200d♂️ Finansal Haber Dedektifi (10. Sınıf)'), ('drag_drop_needs', '🛒 İstek mi İhtiyaç mı? (İlkokul)'), ('stock_market', '📈 Borsa Simülatörü (Çok Yakında)')], max_length=50, null=True, verbose_name='Oyun Seçimi'),
        ),
    ]
