# Generated by Django 5.2.11 on 2026-03-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_content_game_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
