# Generated by Django 5.2.11 on 2026-08-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprogress_play_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='game_code',
            field=models.CharField(blank=True, choices=[('financial_detective', '🕵️\u200d♂️ Finansal Haber Dedektifi (10. Sınıf)'), ('drag_drop_needs', '🛒 İstek mi İhtiyaç mı? (İlkokul)'), ('stock_market', '📈 Borsa Simülatörü (Çok Yakında)'), ('financial_concept_hunt', '🧠 Finansal Sistem: Kavram Avı - Ölçme Değerlendirme')], max_length=50, null=True, verbose_name='Oyun Seçimi'),
        ),
    ]
