# Generated by Django 5.2.11 on 2026-08-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_content_game_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='game_code',
            field=models.CharField(blank=True, choices=[('financial_detective', '🕵️\u200d♂️ Finansal Haber Dedektifi (10. Sınıf)'), ('drag_drop_needs', '🛒 İstek mi İhtiyaç mı? (İlkokul)'), ('stock_market', '📈 Borsa Simülatörü (Çok Yakında)'), ('financial_concept_hunt', '🧠 Finansal Sistem: Kavram Avı - Ölçme Değerlendirme'), ('financial_system_concepts_2', '🧭 Finansal Sistem Kavramlarını Keşfet-2 - Ölçme Değerlendirme'), ('income_type_assessment', '💵 Gelir Türü - Ölçme Değerlendirme'), ('media_literacy_assessment', '📰 Finansal Medya Okuryazarlığı - Ölçme Değerlendirme'), ('credit_card_awareness', '💳 Bilinçli Kredi Kartı Kullanımı'), ('credit_cost_analysis', '🧮 Kredi Maliyeti Analizi'), ('investment_or_consumption', '⚖️ Yatırım mı, Tüketim mi?'), ('information_filter', '🛡️ Bilgi Filtresi - Finansal Medya Okuryazarlığı')], max_length=50, null=True, verbose_name='Oyun Seçimi'),
        ),
    ]
