# Generated by Django 5.2.11 on 2026-08-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_content_game_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='game_code',
            field=models.CharField(blank=True, choices=[('financial_detective', '🕵️\u200d♂️ Finansal Haber Dedektifi (10. Sınıf)'), ('drag_drop_needs', '🛒 İstek mi İhtiyaç mı? (İlkokul)'), ('stock_market', '📈 Borsa Simülatörü (Çok Yakında)'), ('financial_concept_hunt', '🧠 Finansal Sistem: Kavram Avı - Ölçme Değerlendirme'), ('financial_system_concepts_2', '🧭 Finansal Sistem Kavramlarını Keşfet-2 - Ölçme Değerlendirme'), ('income_type_assessment', '💵 Gelir Türü - Ölçme Değerlendirme'), ('media_literacy_assessment', '📰 Finansal Medya Okuryazarlığı - Ölçme Değerlendirme'), ('credit_card_awareness', '💳 Bilinçli Kredi Kartı Kullanımı'), ('credit_cost_analysis', '🧮 Kredi Maliyeti Analizi'), ('investment_or_consumption', '⚖️ Yatırım mı, Tüketim mi?'), ('information_filter', '🛡️ Bilgi Filtresi - Finansal Medya Okuryazarlığı'), ('market_detective', '🐂 Piyasa Dedektifi & Davranışsal Finans Testi'), ('portfolio_master', '💼 Portföy Ustası - Portföy Matrisi & Bitirme Testi'), ('legal_investment_assessment', '📊 Yasal Yatırım Yöntemleri - Ölçme ve Değerlendirme'), ('economic_glossary_match', '📖 Ekonomi Sözlüğü - Sürükle-Bırak Bulmaca'), ('media_glossary_puzzle', '🧩 Finansal Medya Okuryazarlığı - Ekonomi Sözlüğü (Sürükle-Bırak Bulmaca)'), ('income_glossary_puzzle', '💰 Gelir Türleri ve Finansal Kavramlar - Ekonomi Sözlüğü (Sürükle-Bırak Bulmaca)'), ('risk_glossary_puzzle', '🧩 Risk Yönetimi ve Piyasa Kavramları - Ekonomi Sözlüğü (Sürükle-Bırak Bulmaca)'), ('credit_financing_glossary_puzzle', '🧩 Akademik Kredi ve Finansman - Ekonomi Sözlüğü (Sürükle-Bırak Bulmaca)'), ('fraud_hunt_glossary_puzzle', '🎣 Dolandırıcılık Avı - Akademik Finansal Güvenlik (Sürükle-Bırak Bulmaca)'), ('legal_investment_glossary_puzzle', '⚖️ Yasal Yatırım ve Finansal Kavramlar - Ekonomi Sözlüğü (Sürükle-Bırak Bulmaca)'), ('debt_credit_assessment', '🏦 Borçlanma ve Kredi - Ölçme Değerlendirme')], max_length=50, null=True, verbose_name='Oyun Seçimi'),
        ),
    ]
