# Generated by Django 5.2.11 on 2026-08-10 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_content_game_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_type', models.CharField(choices=[('pre_survey', 'Ön Anket'), ('post_survey', 'Son Anket')], max_length=20)),
                ('question_id', models.CharField(max_length=10)),
                ('selected_option', models.CharField(max_length=5)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'survey_type', 'question_id')},
            },
        ),
        migrations.CreateModel(
            name='SurveyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_type', models.CharField(choices=[('pre_survey', 'Ön Anket'), ('post_survey', 'Son Anket')], max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'survey_type')},
            },
        ),
    ]
