# Generated by Django 5.2.11 on 2026-08-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_surveyresponse_surveystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='program_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
