# Generated by Django 5.2.11 on 2026-09-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_content_game_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['order', 'id']},
        ),
    ]
