# Generated by Django 5.2.11 on 2026-09-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_unit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='subtopic',
            options={'ordering': ['order', 'id']},
        ),
    ]
