# Generated by Django 5.2.11 on 2026-09-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_content_options_alter_subtopic_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userbadge',
            constraint=models.UniqueConstraint(fields=('student', 'unit'), name='unique_userbadge_student_unit'),
        ),
        migrations.AddConstraint(
            model_name='userprogress',
            constraint=models.UniqueConstraint(fields=('student', 'content'), name='unique_userprogress_student_content'),
        ),
    ]
