# Generated by Django 5.2.11 on 2026-09-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_content_game_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='game_code',
            field=models.CharField(blank=True, choices=[('financial_detective', '🕵️\u200d♂️ Finansal Medya Okuryazarlığı - 2'), ('drag_drop_needs', '🛒 İstek mi İhtiyaç mı? (İlkokul)'), ('stock_market', '📈 Borsa Simülatörü (Çok Yakında)'), ('risk_hunter', '🎯 Risk Getiri Dengesi - 2'), ('real_data_hunter', '🔍 Finansal Medya Okuryazarlığı - 1'), ('space_shopping_depot', '🚀 Uzay Alışveriş Deposu - İstek & İhtiyaç'), ('risk_return_tradeoff', '📈 Risk Getiri Dengesi - 1'), ('economic_terms', '💡 Finansal Sistem Kavramlarını Keşfet - 1'), ('money_flow', '💸 Finansal Sistem Kavramlarını Keşfet - 2'), ('revenue_matching', '💰 Gelir Türleri - 1'), ('future_choice', '🎯 Gelir Türleri - 2'), ('investment_methods', '💹 Yasal Yatırım Araçlarını Keşfet'), ('scam_detector', '🕵️ Finansal Güvenlik Yöntemleri - 1'), ('financial_concept_hunt', '🧠 Finansal Sistem - Ölçme Değerlendirme 1'), ('financial_system_concepts_2', '🧭 Finansal Sistem - Ölçme Değerlendirme 2'), ('income_type_assessment', '💵 Gelir Türleri - Ölçme Değerlendirme 1'), ('media_literacy_assessment', '📰 Finansal Medya Okuryazarlığı - Ölçme Değerlendirme 2'), ('credit_card_awareness', '💳 Sağlıklı Borçlanma ve Kredi Kullanımı - 1'), ('credit_cost_analysis', '🧮 Sağlıklı Borçlanma ve Kredi Kullanımı - 2'), ('investment_or_consumption', '⚖️ Yatırım mı, Tüketim mi?'), ('information_filter', '🛡️ Finansal Medya Okuryazarlığı - Ölçme Değerlendirme 1'), ('market_detective', '🐂 Risk Getiri Dengesi - Ölçme Değerlendirme 1'), ('portfolio_master', '💼 Risk Getiri Dengesi - Ölçme Değerlendirme 2'), ('legal_investment_assessment', '📊 Yasal Yatırım Araçları - Ölçme ve Değerlendirme'), ('legal_investment_assessment_2', '🔐 Finansal Güvenlik Yöntemleri - Ölçme Değerlendirme 1'), ('economic_glossary_match', '📖 Ekonomi Sözlüğü'), ('media_glossary_puzzle', '🧩 Ekonomi Sözlüğü'), ('income_glossary_puzzle', '💰 Ekonomi Sözlüğü'), ('risk_glossary_puzzle', '🧩 Ekonomi Sözlüğü'), ('credit_financing_glossary_puzzle', '🧩 Ekonomi Sözlüğü'), ('fraud_hunt_glossary_puzzle', '🎣 Ekonomi Sözlüğü'), ('legal_investment_glossary_puzzle', '⚖️ Ekonomi Sözlüğü'), ('debt_credit_assessment', '🏦 Sağlıklı Borçlanma ve Kredi Kullanımı - Ölçme Değerlendirme 2'), ('debt_credit_assessment_2', '🧮 Sağlıklı Borçlanma ve Kredi Kullanımı - Ölçme Değerlendirme 1'), ('asset_liability_glossary_puzzle', '🧩 Ekonomi Sözlüğü'), ('asset_income_expense_assessment', '💻 Aktif ve Pasif Varlık Mantığı - 1'), ('short_long_term_impact', '⏳ Kısa ve Uzun Vadeli Finansal Etki - 1'), ('short_long_term_glossary_puzzle', '🧩 Ekonomi Sözlüğü'), ('investment_consumption_case_assessment', '⚖️ Aktif ve Pasif Varlık Mantığı - Ölçme Değerlendirme 1')], max_length=50, null=True, verbose_name='Oyun Seçimi'),
        ),
    ]
